#!/usr/bin/env python3
"""
EPL Data Bot - template CLI for EPL pipeline outputs.

Usage:
    python3 epl_main.py markdown              # Generate all EPL markdown outputs
    python3 epl_main.py data                  # Generate the consolidated EPL data file
    python3 epl_main.py matches_today         # Generate today's EPL matches file
    python3 epl_main.py quality_report        # Generate the EPL quality report

Options:
    --output DIR        Output directory for markdown files (default: ./data)
"""

import argparse
import sys
from pathlib import Path


LAST_UPDATED = "TEMPLATE UTC"


def render_epl_data(last_updated: str) -> str:
    return f"""# EPL Match Data

**Last Updated:** {last_updated}
**Mode:** Pipeline scaffold

## Data Sources

| Source | Website | Status | Records | Notes |
|--------|---------|--------|---------|-------|
| Fixtures | premierleague.com | TEMPLATE | 0 | Placeholder until fixture ingestion lands |
| Table Snapshot | premierleague.com/tables | TEMPLATE | 0 | Placeholder until standings ingestion lands |
| Team Form | derived rolling window | TEMPLATE | 0 | Placeholder until recent-form features land |
| Availability | club reports and news feeds | TEMPLATE | 0 | Placeholder until availability ingestion lands |
| Market Mapping | execution venue | OPTIONAL | 0 | Placeholder until market adapter lands |

## Candidate Matches

| match_id | kickoff_utc | home_team | away_team | venue | model_home_win | model_draw | model_away_win | quality_state |
|----------|-------------|-----------|-----------|-------|----------------|------------|----------------|---------------|
| example_epl_arsenal_chelsea_2026-03-14 | 2026-03-14 15:00 UTC | Arsenal | Chelsea | Emirates Stadium | TBD | TBD | TBD | TEMPLATE |

## Match Features

| match_id | table_position_delta | points_delta | goal_diff_delta | xg_delta | rest_days_delta | injuries_home | injuries_away | market_alignment |
|----------|----------------------|--------------|-----------------|----------|-----------------|---------------|---------------|------------------|
| example_epl_arsenal_chelsea_2026-03-14 | TBD | TBD | TBD | TBD | TBD | TBD | TBD | TBD |

## Availability Watch

| team | player | status | source | confidence | note |
|------|--------|--------|--------|------------|------|
| Arsenal | Player A | available | placeholder | 0.00 | Replace with normalized availability feed |
| Chelsea | Player B | questionable | placeholder | 0.00 | Replace with normalized availability feed |

## Publishing Notes

- Generated by `python3 epl_main.py markdown --output ./data`
- Replace placeholder rows with live data once EPL ingestion commands land.
"""


def render_epl_matches_today(last_updated: str) -> str:
    return f"""# EPL Matches Today

**Last Updated:** {last_updated}
**Mode:** Pipeline scaffold

## Schedule Sources

| Source | Website | Status | Records | Notes |
|--------|---------|--------|---------|-------|
| Fixtures | premierleague.com | TEMPLATE | 0 | Placeholder until fixture ingestion lands |
| Market Snapshot | execution venue | OPTIONAL | 0 | Placeholder until market adapter lands |

## Matches

| match_id | kickoff_utc | home_team | away_team | venue | status | quality_state |
|----------|-------------|-----------|-----------|-------|--------|---------------|
| example_epl_arsenal_chelsea_2026-03-14 | 2026-03-14 15:00 UTC | Arsenal | Chelsea | Emirates Stadium | scheduled | TEMPLATE |

## Pre-Kickoff Watchlist

| match_id | kickoff_utc | refresh_window | note |
|----------|-------------|----------------|------|
| example_epl_arsenal_chelsea_2026-03-14 | 2026-03-14 15:00 UTC | T-120 to T-15 | Replace with near-kickoff refresh candidates |
"""


def render_epl_quality_report(last_updated: str) -> str:
    return f"""# EPL Quality Report

**Last Updated:** {last_updated}
**Mode:** Pipeline scaffold

## Source Status

| Source | Freshness SLA | Status | Notes |
|--------|---------------|--------|-------|
| Fixtures | <= 6h | TEMPLATE | No live fixture ingestion yet |
| Table Snapshot | <= 24h | TEMPLATE | No live standings snapshot yet |
| Team Form | <= 24h | TEMPLATE | No rolling form dataset yet |
| Availability | <= 3h for same-day matches | TEMPLATE | No live availability ingestion yet |

## Run Summary

| Metric | Value |
|--------|-------|
| total_matches_ingested | 0 |
| fully_scorable_matches | 0 |
| skipped_matches | 0 |
| schema_drift_alerts | 0 |

## Guardrails

| Check | Result | Detail |
|-------|--------|--------|
| missing_fixture_ids | TEMPLATE | No live fixtures evaluated yet |
| ambiguous_team_mapping | TEMPLATE | No live club mapping evaluated yet |
| stale_table_snapshot | TEMPLATE | No live standings snapshot available yet |
| conflicting_availability | TEMPLATE | No live availability sources evaluated yet |

## Skip Reasons

| Reason | Count |
|--------|-------|
| missing_fixture_id | 0 |
| missing_team_mapping | 0 |
| stale_standings | 0 |
| conflicting_availability | 0 |
"""


def write_output(path: Path, contents: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")
    return path


def cmd_data(args: argparse.Namespace) -> int:
    path = write_output(Path(args.output) / "epl_data.md", render_epl_data(LAST_UPDATED))
    print(f"Generated {path}")
    return 0


def cmd_matches_today(args: argparse.Namespace) -> int:
    path = write_output(
        Path(args.output) / "epl_matches_today.md",
        render_epl_matches_today(LAST_UPDATED),
    )
    print(f"Generated {path}")
    return 0


def cmd_quality_report(args: argparse.Namespace) -> int:
    path = write_output(
        Path(args.output) / "epl_quality_report.md",
        render_epl_quality_report(LAST_UPDATED),
    )
    print(f"Generated {path}")
    return 0


def cmd_markdown(args: argparse.Namespace) -> int:
    commands = [cmd_data, cmd_matches_today, cmd_quality_report]
    for command in commands:
        command(args)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="EPL Data Bot - template generator for EPL pipeline outputs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    parser.add_argument(
        "command",
        choices=["markdown", "data", "matches_today", "quality_report"],
        help="Use 'markdown' to write all EPL markdown outputs or an individual file command",
    )
    parser.add_argument(
        "--output",
        default="./data",
        help="Output directory for markdown files (default: ./data)",
    )

    args = parser.parse_args()

    commands = {
        "markdown": cmd_markdown,
        "data": cmd_data,
        "matches_today": cmd_matches_today,
        "quality_report": cmd_quality_report,
    }
    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
