#!/usr/bin/env python3
"""
Tennis Data Bot - template CLI for tennis pipeline outputs.

Usage:
    python3 main_tennis.py markdown         # Generate tennis markdown templates
    python3 main_tennis.py docs             # Print the tennis spec document path

Options:
    --output DIR        Output directory for markdown files (default: ./data)
    --log-dir DIR       Run-log directory (default: ./outputs)
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent
DOCS_PATH = REPO_ROOT / "docs" / "TENNIS_Data_Bot_Spec.md"


def utc_display_timestamp() -> str:
    """Return a human-readable UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def utc_file_timestamp() -> str:
    """Return a compact UTC timestamp for filenames."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%S")


def render_tennis_data(last_updated: str) -> str:
    return f"""# Tennis Match Data

**Last Updated:** {last_updated}
**Mode:** Template scaffold
**Spec:** `docs/TENNIS_Data_Bot_Spec.md`

## Data Sources

| Source | Website | Status | Records | Notes |
|--------|---------|--------|---------|-------|
| Match Schedule | Official ATP/WTA pages | TEMPLATE | 0 | Placeholder until schedule ingestion lands |
| Rankings Snapshot | ATP/WTA rankings | TEMPLATE | 0 | Placeholder until rankings ingestion lands |
| Surface Stats | Historical performance feeds | TEMPLATE | 0 | Placeholder until stats ingestion lands |
| Availability | Tournament/news sources | TEMPLATE | 0 | Placeholder until injury and withdrawal ingestion lands |
| Market Mapping | External execution venue | OPTIONAL | 0 | Placeholder until market adapter lands |

## Candidate Matchups

| match_id | event_name | tour | surface | round | scheduled_utc | player_a | player_b | model_win_prob_a | model_win_prob_b | confidence_grade |
|----------|------------|------|---------|-------|---------------|----------|----------|------------------|------------------|------------------|
| example_masters_r32_player_a_player_b_2026-03-11 | Example Masters | ATP | hard | R32 | 2026-03-11 12:00 UTC | Player A | Player B | TBD | TBD | TBD |

## Matchup Features

| match_id | surface | rank_delta | elo_delta_global | elo_delta_surface | hold_break_composite_delta | form_delta | fatigue_delta | injury_flag_a | injury_flag_b | withdrawal_risk_score_a | withdrawal_risk_score_b |
|----------|---------|------------|------------------|-------------------|----------------------------|------------|---------------|---------------|---------------|-------------------------|-------------------------|
| example_masters_r32_player_a_player_b_2026-03-11 | hard | TBD | TBD | TBD | TBD | TBD | TBD | false | false | TBD | TBD |

## Availability Watch

| player | status | source | source_ts | confidence | note |
|--------|--------|--------|-----------|------------|------|
| Player A | available | placeholder | TBD | 0.00 | Replace with normalized availability feed |
| Player B | questionable | placeholder | TBD | 0.00 | Replace with normalized availability feed |

## Market Mapping

| match_id | external_event_slug | external_market_id | side_a_token | side_b_token | last_seen_price_a | last_seen_price_b | market_snapshot_ts |
|----------|---------------------|--------------------|--------------|--------------|-------------------|-------------------|--------------------|
| example_masters_r32_player_a_player_b_2026-03-11 | TBD | TBD | TBD | TBD | TBD | TBD | TBD |

## Publishing Notes

- Generated by `python3 main_tennis.py markdown --output ./data`
- Replace placeholder rows with live data once tennis ingestion commands land.
"""


def render_tennis_players(last_updated: str) -> str:
    return f"""# Tennis Player Snapshots

**Last Updated:** {last_updated}
**Mode:** Template scaffold
**Spec:** `docs/TENNIS_Data_Bot_Spec.md`

## Snapshot Coverage

| Source | Website | Status | Records | Notes |
|--------|---------|--------|---------|-------|
| Rankings Snapshot | ATP/WTA rankings | TEMPLATE | 0 | Placeholder until rankings ingestion lands |
| Player Context | Cached player metadata | TEMPLATE | 0 | Placeholder until identity mapping lands |

## Player Snapshots

| player_id | name | ranking | elo_global | elo_surface | age | handedness | country |
|-----------|------|---------|------------|-------------|-----|------------|---------|
| example-player-a | Player A | TBD | TBD | TBD | TBD | TBD | TBD |
| example-player-b | Player B | TBD | TBD | TBD | TBD | TBD | TBD |
"""


def render_tennis_matches_today(last_updated: str) -> str:
    return f"""# Tennis Matches Today

**Last Updated:** {last_updated}
**Mode:** Template scaffold
**Spec:** `docs/TENNIS_Data_Bot_Spec.md`

## Schedule Sources

| Source | Website | Status | Records | Notes |
|--------|---------|--------|---------|-------|
| Match Schedule | Official ATP/WTA pages | TEMPLATE | 0 | Placeholder until schedule ingestion lands |
| Fallback Schedule | Mirror provider | OPTIONAL | 0 | Placeholder until fallback schedule adapter lands |

## Matches

| match_id | event_name | tour | surface | round | scheduled_utc | player_a | player_b | best_of | quality_state |
|----------|------------|------|---------|-------|---------------|----------|----------|---------|---------------|
| example_masters_r32_player_a_player_b_2026-03-11 | Example Masters | ATP | hard | R32 | 2026-03-11 12:00 UTC | Player A | Player B | 3 | TEMPLATE |

## Pre-Start Watchlist

| match_id | scheduled_utc | refresh_window | note |
|----------|---------------|----------------|------|
| example_masters_r32_player_a_player_b_2026-03-11 | 2026-03-11 12:00 UTC | T-120 to T-15 | Replace with near-start refresh candidates |
"""


def render_tennis_quality_report(last_updated: str) -> str:
    return f"""# Tennis Quality Report

**Last Updated:** {last_updated}
**Mode:** Template scaffold
**Spec:** `docs/TENNIS_Data_Bot_Spec.md`

## Source Status

| Source | Freshness SLA | Status | Notes |
|--------|---------------|--------|-------|
| Schedule | <= 6h | TEMPLATE | No live schedule ingestion yet |
| Rankings | <= 72h | TEMPLATE | No rankings snapshot yet |
| Stats | <= 7d | TEMPLATE | No historical stats ingestion yet |
| Availability | <= 2h for near-start matches | TEMPLATE | No injury or withdrawal ingestion yet |

## Run Summary

| Metric | Value |
|--------|-------|
| total_matches_ingested | 0 |
| fully_scorable_matches | 0 |
| skipped_matches | 0 |
| schema_drift_alerts | 0 |

## Guardrails

| Check | Result | Detail |
|-------|--------|--------|
| missing_surface | TEMPLATE | No live matches evaluated yet |
| player_identity_mapping | TEMPLATE | No live matches evaluated yet |
| stale_rankings_snapshot | TEMPLATE | No live snapshot available yet |
| conflicting_status_sources | TEMPLATE | No live availability sources evaluated yet |

## Skip Reasons

| Reason | Count |
|--------|-------|
| missing_surface | 0 |
| missing_player_mapping | 0 |
| stale_rankings | 0 |
| conflicting_status | 0 |
"""


def write_text(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def write_run_log(log_dir: Path, last_updated: str, generated_files: list[Path]) -> Path:
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / f"tennis_run_{utc_file_timestamp()}.txt"
    lines = [
        "Tennis template pipeline run",
        f"Last updated: {last_updated}",
        f"Spec path: {DOCS_PATH}",
        "",
        "Generated files:",
    ]
    lines.extend(f"- {path}" for path in generated_files)
    write_text(log_path, "\n".join(lines) + "\n")
    return log_path


def cmd_markdown(args: argparse.Namespace) -> int:
    last_updated = utc_display_timestamp()
    output_dir = Path(args.output)

    renderers = {
        "tennis_data.md": render_tennis_data,
        "tennis_players.md": render_tennis_players,
        "tennis_matches_today.md": render_tennis_matches_today,
        "tennis_quality_report.md": render_tennis_quality_report,
    }

    generated_files = []
    for filename, renderer in renderers.items():
        path = output_dir / filename
        write_text(path, renderer(last_updated))
        generated_files.append(path)

    log_path = write_run_log(Path(args.log_dir), last_updated, generated_files)

    print("Generated tennis markdown templates:")
    for path in generated_files:
        print(f"  - {path}")
    print(f"Run log: {log_path}")
    return 0


def cmd_docs(_: argparse.Namespace) -> int:
    if not DOCS_PATH.exists():
        print(f"Tennis spec document is missing: {DOCS_PATH}", file=sys.stderr)
        return 1

    print(DOCS_PATH)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Tennis Data Bot - template generator for tennis pipeline outputs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    parser.add_argument(
        "command",
        choices=["markdown", "docs"],
        help="Use 'markdown' to write template outputs or 'docs' to print the tennis spec path",
    )
    parser.add_argument(
        "--output",
        default="./data",
        help="Output directory for markdown files (default: ./data)",
    )
    parser.add_argument(
        "--log-dir",
        default="./outputs",
        help="Run-log directory (default: ./outputs)",
    )

    args = parser.parse_args()

    commands = {
        "markdown": cmd_markdown,
        "docs": cmd_docs,
    }
    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
